version: '3'

services:
  proxy:
    image: nginx
    ports:
      - '80:80'
    volumes:
      - ./conf/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
  webdav:
    image: bytemark/webdav
    hostname: web
    restart: always
    depends_on:
      - proxy
    environment:
      AUTH_TYPE: Digest
      USERNAME: frodo
      PASSWORD: bolson
    volumes:
      - ./data/webdav:/var/lib/dav